### ISSUE TITLE
SCHEDULE_EXACT_ALARM problem

### ISSUE THREAD

**Issue by zoelounge** [SwanFlutter/permission_master#1]
Hi, i'm testing your plugin and it seems great, but I've noticed there are issues with the 'SCHEDULE_EXACT_ALARM' permission. 

For example, it keeps causing problems on the simulator, but the same issues appear to occur on physical devices as well, namely: 

No pop-up opens, but instead it redirects you to the settings where you need to enable a flag. Once enabled, I get the following error:

android.permission.SCHEDULE_EXACT_ALARM: DENIED_WITH_RATIONALE 

And after that, if I try again, it redirects me back to the settings where this time the flag is not editable – it says it's active, but in the console I see the following error:"
android.permission.SCHEDULE_EXACT_ALARM: PERMANENT_DENIED.

Can you help me to understand how to activate this particular permissions with your plugin ?
Thanks for all

**Comment by SwanFlutter** [comment]
Hi, thanks for letting me know, I'll try to fix it.

‫‪zoelounge‬‏ ***@***.***‬‏> در تاریخ شنبه ۲۶ آوریل ۲۰۲۵
ساعت ۱۰:۲۸ نوشت:‬

**Comment by SwanFlutter** [comment]
Hello, the problem is solved. I will update you soon.

‫‪swan‬‏ ***@***.***‬‏> در تاریخ یکشنبه ۲۷ آوریل ۲۰۲۵ ساعت
۷:۱۹ نوشت:‬

**Comment by zoelounge** [comment]
Hi, thanks for your interest. 
Please let me know what's the problem is, so I can understand the situation. 

See you later when the issue is resolved.

**Comment by zoelounge** [comment]
Hello, I have just tested the new version and it' seam the problem isn't solved. Sorry
I tested on a real device (OnePlus nord 3 5G and OnePlus 11R )with Android 13 & 14.

> Hello, the problem is solved. I will update you soon.
> 
> ‫‪swan‬‏ ***@***.***‬‏> در تاریخ یکشنبه ۲۷ آوریل ۲۰۲۵ ساعت
> ۷:۱۹ نوشت:‬
> […](#)
